version: '3'

services:
  app:
    build: .
    ports:
      - "5000-5000" #Доступ к Flask напрямую (для отладки)

    volumes:
      - ./uploads:/app/uploads #Общий доступ к загруженным файлам
      - ./converted:/app/converted #Общий доступ к сконвертираванным
      - ./requirements.txt:/app/requirements.txt

  nginx:
    image: nginx:latest
    ports:
      - "80-80" #Получаем доступ через Nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app